#![forbid(unsafe_code)]
use std::collections::HashMap;
use serde::{Deserialize,Serialize};

#[derive(Debug,Clone,Serialize,Deserialize)] pub struct RequestRecord{pub id:String,pub method:String,pub url:String,pub status:Option<u16>,pub duration_ms:u64,pub encoded_bytes:Option<u64>,pub from_cache:bool,pub error:Option<String>,pub initiator:Option<String>}
#[derive(Debug,Clone,Serialize,Deserialize,PartialEq,Eq)] pub enum NetworkIssueKind{Failed,Slow,Duplicate,LargePayload,Cors,MixedContent}
#[derive(Debug,Clone,Serialize,Deserialize)] pub struct NetworkFinding{pub kind:NetworkIssueKind,pub request_ids:Vec<String>,pub message:String,pub confidence:u8}
#[derive(Debug,Clone,Serialize,Deserialize)] pub struct NetworkPolicy{pub slow_ms:u64,pub large_bytes:u64}
impl Default for NetworkPolicy{fn default()->Self{Self{slow_ms:1_500,large_bytes:1_500_000}}}
pub fn analyze(records:&[RequestRecord],policy:&NetworkPolicy)->Vec<NetworkFinding>{let mut out=Vec::new();let mut groups:HashMap<(String,String),Vec<&RequestRecord>>=HashMap::new();for r in records{groups.entry((r.method.clone(),r.url.clone())).or_default().push(r);if r.error.is_some()||r.status.is_some_and(|s|s>=400){out.push(NetworkFinding{kind:NetworkIssueKind::Failed,request_ids:vec![r.id.clone()],message:format!("{} {} failed ({:?})",r.method,r.url,r.status),confidence:100});}if r.duration_ms>=policy.slow_ms{out.push(NetworkFinding{kind:NetworkIssueKind::Slow,request_ids:vec![r.id.clone()],message:format!("{}ms request",r.duration_ms),confidence:100});}if r.encoded_bytes.is_some_and(|b|b>=policy.large_bytes){out.push(NetworkFinding{kind:NetworkIssueKind::LargePayload,request_ids:vec![r.id.clone()],message:format!("large payload: {} bytes",r.encoded_bytes.unwrap()),confidence:100});}if r.error.as_deref().is_some_and(|e|e.to_ascii_lowercase().contains("cors")){out.push(NetworkFinding{kind:NetworkIssueKind::Cors,request_ids:vec![r.id.clone()],message:"CORS failure".into(),confidence:95});}}
for ((_method,_url),items) in groups{if items.len()>=3{out.push(NetworkFinding{kind:NetworkIssueKind::Duplicate,request_ids:items.iter().map(|r|r.id.clone()).collect(),message:format!("{} equivalent requests",items.len()),confidence:82});}}out}
#[cfg(test)]mod tests{use super::*;#[test]fn groups_duplicates(){let r=(0..3).map(|i|RequestRecord{id:i.to_string(),method:"GET".into(),url:"http://x/api".into(),status:Some(200),duration_ms:5,encoded_bytes:None,from_cache:false,error:None,initiator:None}).collect::<Vec<_>>();assert!(analyze(&r,&Default::default()).iter().any(|x|x.kind==NetworkIssueKind::Duplicate));}}
